apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  capacity: 
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "my-storage-class"
  local:
    path: /opt
 # nodeAfinity is used so that pod and pv are created on same node
 # must be used for Dynamic storage and local
  nodeAfinity:
    requied:
      nodeSelectorTerms:
      - matchExpressions:
       - key: kubernetes.io/hostname
         operator: In
         values:
          - worker1
